<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.0.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Sindre H. Øveraas, Alen Colacovic &amp; Sebastian M. Fløysand">

<title>Eurostat EDA</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
span.underline{text-decoration: underline;}
div.column{display: inline-block; vertical-align: top; width: 50%;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>


<script src="Eurostat EDA_files/libs/clipboard/clipboard.min.js"></script>
<script src="Eurostat EDA_files/libs/quarto-html/quarto.js"></script>
<script src="Eurostat EDA_files/libs/quarto-html/popper.min.js"></script>
<script src="Eurostat EDA_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Eurostat EDA_files/libs/quarto-html/anchor.min.js"></script>
<link href="Eurostat EDA_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Eurostat EDA_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Eurostat EDA_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Eurostat EDA_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Eurostat EDA_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Eurostat EDA</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Sindre H. Øveraas, Alen Colacovic &amp; Sebastian M. Fløysand </p>
          </div>
  </div>
    
    
  </div>
  

</header>

<section id="eurostat-eda" class="level2">
<h2 class="anchored" data-anchor-id="eurostat-eda">Eurostat EDA</h2>
<p>In this paper we are going to present an explanatory data analysis of different statistics of selected European countries. We are more specifically going to analyze the European countries Austria (AT), Belgium (BE), Bulgaria (BG), Croatia (HR), Italy (IT), Serbia (RS), and Sweden (SE).</p>
<p>The paper will consist of four parts (assignments), where in the first part we will explore sub-national GDP and regional inequity in our selected countries. For this part we will use data collected from Eurostat. The data for the first part of the paper consists of GDP and population statistics for the years 2000 – 2020, on a sub-regional level i.e., at NUTS 3 level. NUTS (Nomenclature of territorial units for statistics) is the geographical nomenclature subdividing the economic territory of countries in the European Union. These levels consist of NUTS 1, 2 and 3, with 3 representing the smallest territorial units in a country <span class="citation" data-cites="GlossaryNomenclatureTerritorial2021">(<a href="#ref-GlossaryNomenclatureTerritorial2021" role="doc-biblioref"><em>Glossary</em>, 2021</a>)</span>. The remaining parts of this paper i.e., 2, 3 and 4, will be explained continuously and gradually when we eventually get to them later in the paper.</p>
<section id="sub-national-gdp" class="level3">
<h3 class="anchored" data-anchor-id="sub-national-gdp">Sub-National GDP</h3>
<p>To start our analysis of sub-national GDP and regional inequity for our selected countries we must, as mentioned, collect data from Eurostat. We download population by broad age group and sex, as well as gross domestic product at current markets prices, at NUTS 3 level <span class="citation" data-cites="StatisticsEurostat2022a">(<a href="#ref-StatisticsEurostat2022a" role="doc-biblioref"><em>Population on 1 <span>January</span> by Broad Age Group, Sex and <span>NUTS</span> 3 Region</em>, 2022</a>)</span> <span class="citation" data-cites="StatisticsEurostat2022">(<a href="#ref-StatisticsEurostat2022" role="doc-biblioref"><em>Gross Domestic Product (<span>GDP</span>) at Current Market Prices by <span>NUTS</span> 3 Regions</em>, 2022</a>)</span>. After we have added our two datasets to our RStudio project, we can calculate GDP per capita at the NUTS 3 level for the separate countries. This is achieved with dividing the GDP on the number of population figures, and can be presented with the following formula:<br>
</p>
<p><span class="math display">\[
y_i=GDP_i/population_i
\]</span></p>
<div class="cell">

</div>
<div class="cell">

</div>
<p>Looking at the GDP per capita for all countries in the dataset in <a href="#tbl-1">Table&nbsp;1</a>, we find that the difference in population from min to max is big. The difference between Median and Mean is also relatively big witch can indicate that some of the biggest regions has much larger amount of population then the rest and therefore affects the mean and pulls it higher. The fact that the 3rd quartile is just a few thousands away from the mean amplifies our suspicion that we have some outliers with a very high population compared to the rest.</p>
<p>Its reason to believe that high population equals high GDP based on the fact that it is more people that contributes to the GDP. However, this can not be applied in every circumstances. For example Monaco with a population in 2020 of just above 39.000 <span class="citation" data-cites="MonacoPopulation2022">(<a href="#ref-MonacoPopulation2022" role="doc-biblioref"><em>Monaco <span>Population</span> (2022) - <span>Worldometer</span></em>, n.d.</a>)</span> had a GDP on 6.25 billion USD the same year versus Burundi with a GDP on 3.22 billion <span class="citation" data-cites="GDPConstant2015">(<a href="#ref-GDPConstant2015" role="doc-biblioref"><em><span>GDP</span> (Constant 2015 <span>US</span>$) - <span>Burundi</span>, <span>Monaco</span> | <span>Data</span></em>, n.d.</a>)</span> and a population just above 11.89 million <span class="citation" data-cites="BurundiPopulation2022">(<a href="#ref-BurundiPopulation2022" role="doc-biblioref"><em>Burundi <span>Population</span> (2022) - <span>Worldometer</span></em>, n.d.</a>)</span>. The GDP per capita gives us a more accurate measure. in the model above we can see that its a big difference in GDP per capita in each region, this can be caused by a population or a cluster with rich/poor individuals.</p>
<p>We also had some NA values witch we chose to take out of the dataset. NA values may come from the fact that Population or the GDP was not measured this year or was not available when the dataset was made.</p>
<div class="cell">

</div>
<div class="cell">

</div>
<div class="cell">
<div class="cell-output-display">
<p><img src="Eurostat-EDA_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>In the plot above we have taken out the countries that belongs to our selection - Austria (AT), Belgium (BE), Bulgaria (BG), Croatia (HR), Italy (IT), Serbia (RS) and Sweden (SE) - and added them in to a time series from year 2000 - 2020 (X-axis) to compare the evolution of GDP per capita (Y-axis) over the given time period. The data is found and downloaded from Eurostat <span class="citation" data-cites="StatisticsEurostata">(<a href="#ref-StatisticsEurostata" role="doc-biblioref"><em>Statistics | <span>Eurostat</span></em>, n.d.</a>)</span>.</p>
<p>Seven out of eight countries we where given was available for download trough Eurostat, the country witch we are missing is Bosnia and Herzegovina.</p>
<p>From the GG plot we can see that none of the countries have data from the whole time frame, some are missing data from the first years and others are missing from the last years. Serbia only have data from around 2017 to 2019. This might come from the fact that Serbia became an independent republic in 2006 and for that reason has not been collecting og establishing much info around GDP <span class="citation" data-cites="Serbia">(<a href="#ref-Serbia" role="doc-biblioref"><em>Serbia</em>, n.d.</a>)</span>.</p>
<p>The country´s with the highest GDP per capita is Belgium and Sweden, where both countries has experienced growth in GDP per capita over time. Sweden also has had the biggest growth in GDP Per capita compared to the other countries.</p>
<p>From the graphs, the three countries with highest GDP per capita had a noticeable decline around 2008, which is related to the financial crises at this time. Sweden also experiences the largest dip around this time <span class="citation" data-cites="EconomicRecoveryEU">(<a href="#ref-EconomicRecoveryEU" role="doc-biblioref"><em>Economic Recovery of <span>EU</span> Regions After 2008</em>, n.d.</a>)</span></p>
<p>Four of the five countris on the bottom also has experienced growth, just not as significant as Sweden and Belgium. Austria had a big downfall in GDP per capita from year 2000 to 2001, but has had a stable growth since then.</p>
</section>
<section id="bulgaria-gdp" class="level3">
<h3 class="anchored" data-anchor-id="bulgaria-gdp">Bulgaria GDP</h3>
<div class="cell">
<div class="cell-output-display">
<p><img src="Eurostat-EDA_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The table shows the GDP per capita on a NUTS3 level for Bulgaria alone. One Region sticks out from the rest (BG411) with a higher GDP per capita and a higher growth from 2000 to 2020, almost reaching a GDP per capita on 20&nbsp;000. BG411 is a Region in Sofia, capital city of Bulgaria. The reason for this might be because of a better work situation in Sofia with less unemployed people and more business going around <span class="citation" data-cites="StatisticalRegionsEuropean">(<a href="#ref-StatisticalRegionsEuropean" role="doc-biblioref"><em>Statistical Regions in the <span>European Union</span> and Partner Countries</em>, n.d.</a>)</span>.</p>
<p>From year 2000 to around 2005 the other regions had around the same GDP per capita with a similar growth. The following years after 2005 some of the regions have split a bit from others and had a faster growth which laded them to surpass a GDP per capita over 5000 in 2019, some reaching a GDP per capita over 7500 by year 2019.</p>
<div class="cell">
<div class="cell-output-display">

<table>
 <thead>
  <tr>
   <th style="text-align:left;"> Region </th>
   <th style="text-align:right;"> GDP_capita </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> BG411 </td>
   <td style="text-align:right;"> 11904.952 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> BG344 </td>
   <td style="text-align:right;"> 5186.760 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> BG331 </td>
   <td style="text-align:right;"> 5048.607 </td>
  </tr>
</tbody>
</table>

</div>
</div>
<p>Using 2010 as a base point which is after the financial crises, we found that the three regions with highest GDP per capita is BG411 (Sofia), BG344 (Stara Zagora) and BG331 (Varna), all major cities in Bulgaria. These Regions also managed to maintain a good growth in GDP per capita through the years till 2019 <span class="citation" data-cites="StatisticalRegionsEuropean">(<a href="#ref-StatisticalRegionsEuropean" role="doc-biblioref"><em>Statistical Regions in the <span>European Union</span> and Partner Countries</em>, n.d.</a>)</span></p>
<div class="cell">
<div class="cell-output-display">

<table>
 <thead>
  <tr>
   <th style="text-align:left;"> Region </th>
   <th style="text-align:right;"> GDP_capita </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> BG325 </td>
   <td style="text-align:right;"> 2555.374 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> BG311 </td>
   <td style="text-align:right;"> 2701.086 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> BG342 </td>
   <td style="text-align:right;"> 2734.754 </td>
  </tr>
</tbody>
</table>

</div>
</div>
<p>The three regions with lowest GDP Per capita is BG325 (Silistra), BG311 (Vidin) and BG342 (Silven) where BG325 and BG311 both are cities located north in Bulgaria. BG342 is a larger city located more in the middle of Bulgaria a bit southeast <span class="citation" data-cites="StatisticalRegionsEuropean">(<a href="#ref-StatisticalRegionsEuropean" role="doc-biblioref"><em>Statistical Regions in the <span>European Union</span> and Partner Countries</em>, n.d.</a>)</span></p>
</section>
<section id="belgium-gdp" class="level3">
<h3 class="anchored" data-anchor-id="belgium-gdp">Belgium GDP</h3>
<div class="cell">
<div class="cell-output-display">
<p><img src="Eurostat-EDA_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>In Belgium the table shows that it is more variance in GDP per capita from region to region. Most regions have had somewhat of a similar growth trough year 2000 until 2018 before a dip from 2018 to 2020. The dip could be explained by the government formation that started to take place in 2018. We can see that BE100 has a noticeable higher GDP per capita then the closest region. Region BE100 includes the capital city of Belgium, Brussel <span class="citation" data-cites="brzozowskiBelgiumBreaks16month2020">(<a href="#ref-brzozowskiBelgiumBreaks16month2020" role="doc-biblioref">Brzozowski, 2020</a>)</span> <span class="citation" data-cites="StatisticalRegionsEuropean">(<a href="#ref-StatisticalRegionsEuropean" role="doc-biblioref"><em>Statistical Regions in the <span>European Union</span> and Partner Countries</em>, n.d.</a>)</span>.</p>
<div class="cell">
<div class="cell-output-display">

<table>
 <thead>
  <tr>
   <th style="text-align:left;"> Region </th>
   <th style="text-align:right;"> GDP_capita </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> BE211 </td>
   <td style="text-align:right;"> 41353.08 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> BE241 </td>
   <td style="text-align:right;"> 39306.81 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> BE234 </td>
   <td style="text-align:right;"> 38714.12 </td>
  </tr>
</tbody>
</table>

</div>
</div>
<p>The three regions with the largest GDP in Belgium in 2010, after the financial crises, is BE100 (Brussel), BE211 (Antwerpen) and BE241 (Halle-Vilvoorde) <span class="citation" data-cites="StatisticalRegionsEuropean">(<a href="#ref-StatisticalRegionsEuropean" role="doc-biblioref"><em>Statistical Regions in the <span>European Union</span> and Partner Countries</em>, n.d.</a>)</span> . Brussel being the capital and Halle-Vilvoorde being a region located around Brussel indicates that it is generally lower unemployment and more business in this area. Antwerpwen is located more north in Belgium is a major city when it comes to seaports. Its also well known for its diamond industry <span class="citation" data-cites="AntwerpHistoryDiamonds">(<a href="#ref-AntwerpHistoryDiamonds" role="doc-biblioref"><em>Antwerp | <span>History</span>, <span>Diamonds</span>, <span>Port</span>, &amp; <span>Points</span> of <span>Interest</span> | <span>Britannica</span></em>, n.d.</a>)</span></p>
<div class="cell">
<div class="cell-output-display">

<table>
 <thead>
  <tr>
   <th style="text-align:left;"> Region </th>
   <th style="text-align:right;"> GDP_capita </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> BE334 </td>
   <td style="text-align:right;"> 15211.81 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> BE353 </td>
   <td style="text-align:right;"> 15727.11 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> BE345 </td>
   <td style="text-align:right;"> 15796.64 </td>
  </tr>
</tbody>
</table>

</div>
</div>
<p>The three regions with the smallest GDP per capita in Belgum by 2010 was BE334 (Waremme), BE353 (Philippeville) and BE345 (Virton) <span class="citation" data-cites="StatisticalRegionsEuropean">(<a href="#ref-StatisticalRegionsEuropean" role="doc-biblioref"><em>Statistical Regions in the <span>European Union</span> and Partner Countries</em>, n.d.</a>)</span> . Philippeville and Virton is both located north and border to France. Waremme is located more mid-east</p>
</section>
<section id="section" class="level3">
<h3 class="anchored" data-anchor-id="section"></h3>
<p>Austria GDP</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="Eurostat-EDA_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Austria has a more aggregated graphs, even though it is a gap between highest and lowest, the GDP per capita development is more equal. We can see that some regions has experience a bit more ups and downs trough the years and most regions has a dip around the financial crises in 2008.</p>
<div class="cell">
<div class="cell-output-display">

<table>
 <thead>
  <tr>
   <th style="text-align:left;"> Region </th>
   <th style="text-align:right;"> GDP_capita </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> AT312 </td>
   <td style="text-align:right;"> 46232.41 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> AT323 </td>
   <td style="text-align:right;"> 45690.26 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> AT221 </td>
   <td style="text-align:right;"> 41579.52 </td>
  </tr>
</tbody>
</table>

</div>
</div>
<p>AT312 (Linz-Wels), AT130 (Wien) and AT323 (Salzburg) is the Regions with the highest scoring GDP per capita in 2010. They have held a similar pattern and GDP per capita from 2000 to 2020 <span class="citation" data-cites="StatisticalRegionsEuropean">(<a href="#ref-StatisticalRegionsEuropean" role="doc-biblioref"><em>Statistical Regions in the <span>European Union</span> and Partner Countries</em>, n.d.</a>)</span></p>
<div class="cell">
<div class="cell-output-display">

<table>
 <thead>
  <tr>
   <th style="text-align:left;"> Region </th>
   <th style="text-align:right;"> GDP_capita </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> AT125 </td>
   <td style="text-align:right;"> 18212.92 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> AT111 </td>
   <td style="text-align:right;"> 19680.49 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> AT313 </td>
   <td style="text-align:right;"> 20272.85 </td>
  </tr>
</tbody>
</table>

</div>
</div>
<p>The three lowest scoring regions are AT125 (Weinviertel), AT111 (Mittelburgenland) and AT313 (Mühlviertel) witch all is more greener areas. Both Weinviertel and Mühlviertel are located north and boarders to the Czech Republic while Mittelburgenland southeast and boarders to Hungary <span class="citation" data-cites="StatisticalRegionsEuropean">(<a href="#ref-StatisticalRegionsEuropean" role="doc-biblioref"><em>Statistical Regions in the <span>European Union</span> and Partner Countries</em>, n.d.</a>)</span> .</p>
</section>
<section id="croatia-gdp" class="level3">
<h3 class="anchored" data-anchor-id="croatia-gdp">Croatia GDP</h3>
<div class="cell">
<div class="cell-output-display">
<p><img src="Eurostat-EDA_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The graphs for Croatia shows that the financial crises also had an impact on the GDP per capita in 2008 until 2012/2013 before the GDP per capita startet do climb again before it dips again around 2018. We can see that region HR036 and HR031 has GDP per capita that lays a bit higher than the other regions for the most part.</p>
<p>However, region HR037 and HR032 also had some good years. Croatia has also fewer regions with available DGP data on a nuts3 level then the other countries.</p>
<div class="cell">
<div class="cell-output-display">

<table>
 <thead>
  <tr>
   <th style="text-align:left;"> Region </th>
   <th style="text-align:right;"> GDP_capita </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> HR036 </td>
   <td style="text-align:right;"> 13287.36 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> HR031 </td>
   <td style="text-align:right;"> 12920.32 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> HR037 </td>
   <td style="text-align:right;"> 10320.23 </td>
  </tr>
</tbody>
</table>

</div>
</div>
<p>The topvthree regions in 2010 measured by GDP per capita is HR036 (istarska županija), HR031 (Primorsko-goranska županija) and HR037 (dubrovnik-neretva) <span class="citation" data-cites="StatisticalRegionsEuropean">(<a href="#ref-StatisticalRegionsEuropean" role="doc-biblioref"><em>Statistical Regions in the <span>European Union</span> and Partner Countries</em>, n.d.</a>)</span>. istarska županija is big on processing industry, tourism and trade <span class="citation" data-cites="Economy">(<a href="#ref-Economy" role="doc-biblioref"><em>Economy</em>, n.d.-a</a>)</span>.</p>
<p>Dubrovnik-Neretva is the capital of Croatias and are also big on tourism, but also makes a living out of hospitality industry, agriculture and maritime indisutry <span class="citation" data-cites="Economya">(<a href="#ref-Economya" role="doc-biblioref"><em>Economy</em>, n.d.-b</a>)</span>.</p>
<div class="cell">
<div class="cell-output-display">

<table>
 <thead>
  <tr>
   <th style="text-align:left;"> Region </th>
   <th style="text-align:right;"> GDP_capita </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> HR034 </td>
   <td style="text-align:right;"> 7877.665 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> HR032 </td>
   <td style="text-align:right;"> 7971.199 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> HR035 </td>
   <td style="text-align:right;"> 8363.857 </td>
  </tr>
</tbody>
</table>

</div>
</div>
<p>On the other side, the three regions with lowest GDP per capita by 2010 is HR034 (Šibensko-kninska županija), HR032 (Ličko-senjska županija) and HR035 (Splitsko-dalmatinska županija). All are located south in Croatia by the coast and boarders to Bosnia-Hercegovina <span class="citation" data-cites="StatisticalRegionsEuropean">(<a href="#ref-StatisticalRegionsEuropean" role="doc-biblioref"><em>Statistical Regions in the <span>European Union</span> and Partner Countries</em>, n.d.</a>)</span> .</p>
</section>
<section id="italy-gdp" class="level3">
<h3 class="anchored" data-anchor-id="italy-gdp">Italy GDP</h3>
<div class="cell">
<div class="cell-output-display">
<p><img src="Eurostat-EDA_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Italy consists of many NUTS3 Regions. We piced out only the 500 biggest and used them in our plot. Some of the regions in the plot don’t hav GDP per capita data for the whole-time frame. We can see that is a big difference in the Regions at the bottom and the one on top. The top Region ITC4C (Milano) also stands out from the rest with a higher GDP per capita at all times between year 2000 and 2020 <span class="citation" data-cites="StatisticalRegionsEuropean">(<a href="#ref-StatisticalRegionsEuropean" role="doc-biblioref"><em>Statistical Regions in the <span>European Union</span> and Partner Countries</em>, n.d.</a>)</span> . We can also see that it is some what of a dip around 2011 too. This could come from Sovereign Debt <span class="citation" data-cites="romano2011CrisisItaly2021">(<a href="#ref-romano2011CrisisItaly2021" role="doc-biblioref">Romano, 2021</a>)</span> and later on tension between Russia and Ukraine witch impacted exports <span class="citation" data-cites="ewingItalyFallsBack2014">(<a href="#ref-ewingItalyFallsBack2014" role="doc-biblioref">Ewing and Pianigiani, 2014</a>)</span>.</p>
<div class="cell">
<div class="cell-output-display">

<table>
 <thead>
  <tr>
   <th style="text-align:left;"> Region </th>
   <th style="text-align:right;"> GDP_capita </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> ITC4C </td>
   <td style="text-align:right;"> 52696.50 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ITI43 </td>
   <td style="text-align:right;"> 39391.67 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ITH55 </td>
   <td style="text-align:right;"> 36686.77 </td>
  </tr>
</tbody>
</table>

</div>
</div>
<p>TC4C (Milano), ITH10 (Bolzano-Bozen) and ITI43 (Rome) are the three regions in Italy with the highest GDP per capita by 2010 <span class="citation" data-cites="StatisticalRegionsEuropean">(<a href="#ref-StatisticalRegionsEuropean" role="doc-biblioref"><em>Statistical Regions in the <span>European Union</span> and Partner Countries</em>, n.d.</a>)</span> . Milano are one of the biggest fashion cites in the world, and arranges “Fashion-week” every year witch draws visitors from all over the world <span class="citation" data-cites="MilanHistoryPopulation">(<a href="#ref-MilanHistoryPopulation" role="doc-biblioref"><em>Milan | <span>History</span>, <span>Population</span>, <span>Climate</span>, &amp; <span>Facts</span> | <span>Britannica</span></em>, n.d.</a>)</span>. Bolzano-Bozen is a rich city and focus on quality agriculture, producing wine, fruit and dairy products. Tourism is also a source of income for the city <span class="citation" data-cites="BolzanoBozenTrentinoAlto">(<a href="#ref-BolzanoBozenTrentinoAlto" role="doc-biblioref"><em>Bolzano - <span>Bozen</span>, <span>Trentino-Alto Adige</span>, <span>Italy</span></em>, n.d.</a>)</span>. Rome is a powerful economic force in Italy and are the center for politics. The main industry in Rome are service <span class="citation" data-cites="EconomyItaly">(<a href="#ref-EconomyItaly" role="doc-biblioref"><em>Economy <span>In Italy</span></em>, n.d.</a>)</span>.</p>
<div class="cell">
<div class="cell-output-display">

<table>
 <thead>
  <tr>
   <th style="text-align:left;"> Region </th>
   <th style="text-align:right;"> GDP_capita </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> ITG14 </td>
   <td style="text-align:right;"> 14502.91 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ITF48 </td>
   <td style="text-align:right;"> 14831.01 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ITF64 </td>
   <td style="text-align:right;"> 15105.24 </td>
  </tr>
</tbody>
</table>

</div>
</div>
<p>Out of the 500 Regions we picked out, ITG4 (Agrigento), ITF48 (Barletta-Andria-Trani) and ITF64 (Catanzaro) had the lowest GDP per capita in 2010 <span class="citation" data-cites="StatisticalRegionsEuropean">(<a href="#ref-StatisticalRegionsEuropean" role="doc-biblioref"><em>Statistical Regions in the <span>European Union</span> and Partner Countries</em>, n.d.</a>)</span> . All three regions are located South in Italy. Agrigento´s economic is focused around Sulfur and potash mining, tourism and agriculture <span class="citation" data-cites="AgrigentoItalyBritannica">(<a href="#ref-AgrigentoItalyBritannica" role="doc-biblioref"><em>Agrigento | <span>Italy</span> | <span>Britannica</span></em>, n.d.</a>)</span>. Barletta-Andria-Trani have cities such as Barletta where the economy comes from producing cement and other similar products <span class="citation" data-cites="WhereBarlettaBarlettaAndriaTrani">(<a href="#ref-WhereBarlettaBarlettaAndriaTrani" role="doc-biblioref"><em>Where Is <span>Barletta</span>, <span>Barletta-Andria-Trani</span>, <span>Italy</span> on <span>Map Lat Long Coordinates</span></em>, n.d.</a>)</span>. The lowest scoring region, Catanzaro, have farming as one of their main industries <span class="citation" data-cites="CalabriaRegionItaly">(<a href="#ref-CalabriaRegionItaly" role="doc-biblioref"><em>Calabria | Region, <span>Italy</span> | <span>Britannica</span></em>, n.d.</a>)</span>.</p>
</section>
<section id="serbia-gdp" class="level3">
<h3 class="anchored" data-anchor-id="serbia-gdp">Serbia GDP</h3>
<div class="cell">
<div class="cell-output-display">
<p><img src="Eurostat-EDA_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>As mentioned earlier, Serbia only provides us GDP data from 2017-2019. Looking at the graphs, 2018 seems to be a breaking point for the GDP per capita where some regions experiences growth, while other experiences a decline in GDP Per capita.</p>
<div class="cell">
<div class="cell-output-display">

<table>
 <thead>
  <tr>
   <th style="text-align:left;"> Region </th>
   <th style="text-align:right;"> GDP_capita </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> RS221 </td>
   <td style="text-align:right;"> 5088.925 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> RS214 </td>
   <td style="text-align:right;"> 4952.876 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> RS226 </td>
   <td style="text-align:right;"> 4916.722 </td>
  </tr>
</tbody>
</table>

</div>
</div>
<p>The three regions with the highest GDP per capita in Serbia, here measured for year 2017 was RS221 (Borska oblast), RS214 (Moravička oblast) and RS226 (Pirotska oblast) <span class="citation" data-cites="StatisticalRegionsEuropean">(<a href="#ref-StatisticalRegionsEuropean" role="doc-biblioref"><em>Statistical Regions in the <span>European Union</span> and Partner Countries</em>, n.d.</a>)</span>.</p>
<div class="cell">
<div class="cell-output-display">

<table>
 <thead>
  <tr>
   <th style="text-align:left;"> Region </th>
   <th style="text-align:right;"> GDP_capita </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> RS228 </td>
   <td style="text-align:right;"> 2534.092 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> RS227 </td>
   <td style="text-align:right;"> 2609.823 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> RS224 </td>
   <td style="text-align:right;"> 2753.131 </td>
  </tr>
</tbody>
</table>

</div>
</div>
<p>The thre lowest scoring regions in Serbia in 2017 was RS228 (Pčinjska oblast), RS227 (Pirotska oblast) and RS224 (Jablanička oblast) <span class="citation" data-cites="StatisticalRegionsEuropean">(<a href="#ref-StatisticalRegionsEuropean" role="doc-biblioref"><em>Statistical Regions in the <span>European Union</span> and Partner Countries</em>, n.d.</a>)</span></p>
</section>
<section id="sweden-gdp" class="level3">
<h3 class="anchored" data-anchor-id="sweden-gdp">Sweden GDP</h3>
<div class="cell">
<div class="cell-output-display">
<p><img src="Eurostat-EDA_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The Swedish statistics show Stockholm as superior to the other regions both in GDP, GDP per capita and population. As expected from the capital of Sweden. This is where the main industrial clusters are located, which draws population and GDP higher. What is noteable her is that the neighbour region SE122 (Sódermanland) which borders Stockholm, is second to last at the bottom with half the GDP per Capita compared to Stockholm. We belive this has a connection to the employment rates and there would be a bigger atraction for workers to employ in stockholm. Another interesting bit about the swedish GDP per capita is that their smallest region by population (2019) is Gotland (SE214) with 59 249, comparing Gotland to Stockholm there is almost 40x more people in Stockholm (2 344 124). The GDP is 2050,4 against 151 284,4 which is aprox a 74x difference in favor Stockholm. This makes the GDP per capita 34 603 against<br>
Stockholm´s 64&nbsp;537, less then a 2x difference <span class="citation" data-cites="StatisticalRegionsEuropean">(<a href="#ref-StatisticalRegionsEuropean" role="doc-biblioref"><em>Statistical Regions in the <span>European Union</span> and Partner Countries</em>, n.d.</a>)</span>.</p>
<div class="cell">
<div class="cell-output-display">

<table>
 <thead>
  <tr>
   <th style="text-align:left;"> Region </th>
   <th style="text-align:right;"> GDP_capita </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> SE332 </td>
   <td style="text-align:right;"> 43768.31 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> SE232 </td>
   <td style="text-align:right;"> 38740.05 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> SE322 </td>
   <td style="text-align:right;"> 37522.62 </td>
  </tr>
</tbody>
</table>

</div>
</div>
<p>As previously we chosed 2010 as point, where the recovery from the financial crisis was in route. Stockholm had a GDP per capita of 56036,50 at that time while Norrbottens came in second with 43768,31 and Vastra Gotaland at third with 38740,05.</p>
<div class="cell">
<div class="cell-output-display">

<table>
 <thead>
  <tr>
   <th style="text-align:left;"> Region </th>
   <th style="text-align:right;"> GDP_capita </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> SE214 </td>
   <td style="text-align:right;"> 30273.33 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> SE311 </td>
   <td style="text-align:right;"> 31466.64 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> SE122 </td>
   <td style="text-align:right;"> 31673.87 </td>
  </tr>
</tbody>
</table>

</div>
</div>
<p>The regions with the lowest GDP per capita in 2010 were fairly close, and little that differed them from eachoter aswell as some other regions.</p>
</section>
<section id="regions-with-highest-gdp" class="level3">
<h3 class="anchored" data-anchor-id="regions-with-highest-gdp">10 regions with highest GDP</h3>
<div class="cell">
<div class="cell-output-display">
<p><img src="Eurostat-EDA_files/figure-html/unnamed-chunk-27-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Comparing the regions with the highest GDP per capita between the countries, we see BE100 (Brussels) with a GDP that was rising well above 70 000 before the corona pandemic, and was slightly lower than 70 000 in 2020.From this dataset among the highest gdp per capita regions, it was only Brussels and Antwerp that had data available until 2020. AT323 which is Salzburg, more concretely Salzburg und Umgebung [@NUTSStatisticalRegions2022], had a population of 366´866 in 2019, which is a great difference compared to SE110 - Stockholm with a population of 2´344´124 in 2019. A considerable difference, showing how the GDP per capita is fairly close to eachother even though the aforementioned population difference.</p>
</section>
<section id="regions-with-lowest-gdp" class="level3">
<h3 class="anchored" data-anchor-id="regions-with-lowest-gdp">10 regions with lowest GDP</h3>
<div class="cell">
<div class="cell-output-display">
<p><img src="Eurostat-EDA_files/figure-html/unnamed-chunk-28-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>We want to clarify that there was insufficent data when it came to Bosnia &amp; Hercegovina, which could have been a contender for the lowest GDP per Capita in some regions. Same goes for Serbia, where we chose to withold them from this top 10 list because a lack of information pre- 2017.<br>
</p>
<p><br>
The 10 regions with the lowest GDP per capita shows us they are <em>all</em> located in Bulgaria<strong>.</strong> Eight of the lowest GDP per capita regions are located in Nuts 1 - BG3 (Northern &amp; Eastern Bulgaria). BG 3 is divided into 4 Nuts 2 regions : (BG31)Northwestern, (BG32)Northern Central, (BG33) Northeastern, (BG34) Southeastern. BG31 has three provinces that are on our top 10list; Vidin Province(311), Montana Province(312) and Pleven Province(314). It is clear to see that the pattern for where the GDP per capita is low, is around the Eastern areas, Northeast, central east and southeast. These are also some of the areas that are furthest away from the Capital. The interesting part of this diagram is that around 2004, the GDP per capita of the regions were fairly aligned with eachother at 2000, before they started ascending and increasing the gap.</p>
</section>
</section>
<section id="regional-inequity" class="level2">
<h2 class="anchored" data-anchor-id="regional-inequity">Regional inequity</h2>
<p>Regional inequity refers to skewed distribution and the differences in quality of life, wealth and general living standards among individuals in a region. To determine regional inequity for our selected countries, we calculate the population-weighted GDP Gini coefficients (<span class="math inline">\(GINIW_j\)</span>). The coefficients can have values ranging from 0 to 1. The value 0 corresponds to no inequity, and the higher the coefficient, the higher inequity appears in the respective country/ region. The value 1 corresponds to absolute inequity. The coefficients are calculated by the following formula:</p>
<p><span class="math display">\[
GINIW_j=\frac{1}{2 \bar{y_j}} \sum_{i}^{n_j}\sum_{l}^{n_j}\frac{p_i}{P_j} \frac{p_l}{P_j} |y_i-y_l|
\]</span></p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(<span class="fu">summary</span>(GDP_Per_Capita <span class="sc">%&gt;%</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(GINI_NUTS2)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">

<table>
 <thead>
  <tr>
   <th style="text-align:left;">   </th>
   <th style="text-align:left;">   GINI_NUTS2 </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;"> Min.   :6.130e-06 </td>
  </tr>
  <tr>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;"> 1st Qu.:3.642e-02 </td>
  </tr>
  <tr>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;"> Median :6.392e-02 </td>
  </tr>
  <tr>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;"> Mean   :7.356e-02 </td>
  </tr>
  <tr>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;"> 3rd Qu.:1.068e-01 </td>
  </tr>
  <tr>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;"> Max.   :2.352e-01 </td>
  </tr>
</tbody>
</table>

</div>
</div>
<p>The summary statistics above give us the descriptive figures for all our selected countries combined, throughout the whole period of 2000 - 2020. Based on the statistics, we can note that the lowest coefficient is equal to 0, meaning that there are some regions where inequality is absent. We can also observe that the highest inequality throughout the entire period is 0.235. The mean of the Gini coefficients are 0.071.</p>
<div class="cell">
<div class="cell-output-display">

<table>
 <thead>
  <tr>
   <th style="text-align:left;">   </th>
   <th style="text-align:left;">   GINI_NUTS2 </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;"> Min.   :0.001086 </td>
  </tr>
  <tr>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;"> 1st Qu.:0.038156 </td>
  </tr>
  <tr>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;"> Median :0.066395 </td>
  </tr>
  <tr>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;"> Mean   :0.074680 </td>
  </tr>
  <tr>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;"> 3rd Qu.:0.111032 </td>
  </tr>
  <tr>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;"> Max.   :0.235240 </td>
  </tr>
</tbody>
</table>

</div>
</div>
<p>Based on this data we see that all of the countries are collectively within adequate equality or better. where the min, 1st q, median and mean are all below the 0,1 point. The max is at 0,23524 which you can see on the graphs under, and is within the Bulgarian regions. Seeing how all of the top 10 regions that scored the lowest were from Bulgaria, it does not come of as a shock, that they also have the highest GINI score. The capital of Bulgaria, Sofia, has more than twice of the average GDP per capita of the remaining regions, and for some of the lower regions, more than 5times the amount.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="Eurostat-EDA_files/figure-html/unnamed-chunk-31-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Density distribution of all coefficients in all selected countries. We can observe that the density plot above matches our summary statistics of the coefficients. The density is at peak, at aproximately 0,03 GINI, reaching almost 10 in density. this signalizes that there is adequate equality between regions.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="Eurostat-EDA_files/figure-html/unnamed-chunk-32-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>In this plot we see 4 countries touching the 0,00 GINI point, symbolizeing perfect equality for some regions, with one stretching beyon 0,2 going towards adequate equality. Further on we see Sweden being the country that scored the best with having the biggest density closest to 0,00 and we can with that confirm Sweden being the country that is closest to perfect equality between its own regions.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="Eurostat-EDA_files/figure-html/unnamed-chunk-33-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>A closer look at Sweden and we see their regions and how their GINI index has been throughout the years.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="Eurostat-EDA_files/figure-html/unnamed-chunk-34-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Comparing this plot to the one above you see there is a bigger diversity and inequality compared to Sweden. This is still well within limits of adequate equality, and only one region that crosses the 0,1 line.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="Eurostat-EDA_files/figure-html/unnamed-chunk-35-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The Bulgarian GINI plot which is the one with the biggest spread between our three plots, where the range is from 0,04 to 0,235. This visualization shows us how the plot excelled during the years and created a bigger gap with the years. The overall mean also increased with the years implying they are moving further away from perfect equality.</p>
<section id="conclusion" class="level3">
<h3 class="anchored" data-anchor-id="conclusion">Conclusion</h3>
<p>In conclusion our regions do have some differences as well as similarities, some of the patterns we noticed were the capitals of the respected countries, were usually on top of the GDP per capita compared to their regions. This for several reasons as we mentioned earlier, how the industrial clusters usually are located there and attract more workers. Further on when we went deeper into detail, we saw the GINI coefficients of the countries and their regions, we can concluded that they were all within the limit of adequate equality, while some were close and even on perfect equality.</p>
</section>
</section>
<section id="growth-and-inequity" class="level2">
<h2 class="anchored" data-anchor-id="growth-and-inequity">Growth and inequity</h2>
<p>For the second part of this paper we will explore growth and inequity for our subset of selected countries. This part will mainly consist of regression analyses, where we will start with an analysis of the effect of regional development <span class="math inline">\(y_j\)</span> on the regional inequality <span class="math inline">\(GINIW_j\)</span>. Later in this part we will estimate a multiple linear regression model with other variables that might determine inequity, which we will explain in more detail later. For the sake of simplicity, we will only concentrate on one year in these analyses, the year 2010.</p>
<p>One can argue that regional development has a significant connection to regional economic growth. GDP per capita is widely used by economists to gauge the health of an economy. According to the United Nations Statistics Division the purpose of the GDP per capita indicator is to “…measure the level of total economic output relative to the population of a country” <span class="citation" data-cites="unitednationsstatisticsdivisionGROSSDOMESTICPRODUCT2007">(<a href="#ref-unitednationsstatisticsdivisionGROSSDOMESTICPRODUCT2007" role="doc-biblioref">Division, 2007</a>)</span>. It is further explained that GDP per capita can be used as an indicator to measure the allocation of how total production of a country/ region can be shared among the population. GDP per capita is thus a powerful simple indicator of economic growth, and it can be argued that it can also be used as an indicator for development in inequality.</p>
<div class="cell">

</div>
<div class="cell">

</div>
<div class="cell">

</div>
<div class="cell">

</div>
<section id="the-effect-of-regional-economic-development-on-regional-inequality" class="level3">
<h3 class="anchored" data-anchor-id="the-effect-of-regional-economic-development-on-regional-inequality">The effect of regional economic development on regional inequality</h3>
<p>As mentioned in the introduction of this part of the paper, we will carry out a simple regression model and explore the effect of regional economic development <span class="math inline">\(y_j\)</span> on regional inequality <span class="math inline">\(GINIW_j\)</span>. We will do this in order to gain an understanding of the connection between economic growth indicators such as GDP per capita and inequality might have. We will explore if higher GDP per capita may lead to less or greater inequality, and also gain an understanding to what extent these variables are related.</p>
<p>The simple regression model for this part is structured in the following way:</p>
<p><span class="math display">\[
Y_i = β_1 + β_2X_i + ε_i
\]</span></p>
<ul>
<li><span class="math inline">\(Y_i\)</span> as the dependent/ explained variable</li>
<li><span class="math inline">\(X_i\)</span> as the independent/ explanatory variable</li>
<li><span class="math inline">\(β_1\)</span> as the intercept/ constant</li>
<li><span class="math inline">\(β_2\)</span> as the slope coefficient</li>
<li><span class="math inline">\(ε_i\)</span> as the error/ disturbance term</li>
</ul>
<div class="cell">
<div class="cell-output-display">

<table class="huxtable" style="border-collapse: collapse; border: 0px; margin-bottom: 2em; margin-top: 2em; ; margin-left: auto; margin-right: auto;  " id="tab:unnamed-chunk-40">
<colgroup><col><col><col><col><col><col><col><col></colgroup><tbody><tr>
<th style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0.8pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;"></th><th style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0.8pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">AT</th><th style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0.8pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">BE</th><th style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0.8pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">BG</th><th style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0.8pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">HR</th><th style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0.8pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">IT</th><th style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0.8pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">SE</th><th style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0.8pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">CC</th></tr>
<tr>
<th style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">GDP_capita_NUTS2</th><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">-0.000&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">-0.000&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">0.000 ***</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">0.000 ***</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">0.000&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">-0.000 *&nbsp;&nbsp;</td></tr>
<tr>
<th style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;"></th><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(0.000)</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(0.000)</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(0.000)&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(0.000)&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(0.000)</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(0.000)&nbsp;&nbsp;&nbsp;</td></tr>
<tr>
<th style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">const.</th><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">0.144&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">0.128&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">-0.019&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">0.115 ***</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">-0.039&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">-0.063&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">0.089 ***</td></tr>
<tr>
<th style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;"></th><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(0.111)</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(0.059)</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(0.012)&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(0.000)&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(0.023)&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(0.066)</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(0.015)&nbsp;&nbsp;&nbsp;</td></tr>
<tr>
<th style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">N</th><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">8&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">7&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">6&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">2&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">34&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">14&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">71&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td></tr>
<tr>
<th style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.8pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">R2</th><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.8pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">0.043&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.8pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">0.151&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.8pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">0.974&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.8pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">0.000&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.8pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">0.330&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.8pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">0.119&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.8pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">0.064&nbsp;&nbsp;&nbsp;&nbsp;</td></tr>
<tr>
<th colspan="8" style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0.8pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">Note:  *** p &lt; 0.001;  ** p &lt; 0.01;  * p &lt; 0.05 T statistics in brackets.</th></tr>
</tbody></table>

</div>
</div>
<p>As shown in the regression table, we have the intercepts and slope coefficient of all separate regions of regional economic development (<span class="math inline">\(X_i\)</span>) on regional inequality (<span class="math inline">\(Y_i\)</span>) (excluding Serbia (RS) because of insufficient data). In alphabetical order of country codes, the table shows the intercept, slope, number of observations and the coefficient of determination (<span class="math inline">\(R^2\)</span>) for the different NUTS2 country regions. The last model of the table Countries Combined (CC), is generated from the combined data from all regions regardless of country. We have chosen to ignore observations where GINI = 0, as we believe these values are due to missing data.</p>
<p>The negative slope coefficients of the regression analysis show us that there is a tendency for less regional inequality in Austria and Belgium when regional economic development increases. Using Austria as an example, with the slope coefficient of -0.043, the dependent variable of regional inequality (<span class="math inline">\(Y_i\)</span>) will decrease with 0.043%, when the independent variable of regional economic development (<span class="math inline">\(X_i\)</span>) increases by 1%. In contrast, the simple regression analysis show that Bulgaria and Italy have a positive slope coefficients, telling us that inequality actually increases when economic regional development increases. For all the countries combined, we observe a negative slope coefficient of -0.023, implying once again that increase in economic development reduces inequality overall for our subset of countries.</p>
</section>
<section id="goodness-of-fit-for-estimated-regression-model" class="level3">
<h3 class="anchored" data-anchor-id="goodness-of-fit-for-estimated-regression-model">Goodness of fit for estimated regression model</h3>
<p>To determine the goodness of fit for the estimated simple regression models in the table above we look at the coefficient of determination <span class="math inline">\(R^2\)</span>. The coefficient of determination tells us how close the data are to the fitted regression line, and represents the quantity of the variance for the dependent variable that is explained by the independent variable. The <span class="math inline">\(R^2\)</span> can have values ranging from 0 to 1. Should the coefficient as an example be 0.7, this means around 70% of the dependent variable can be explained by the independent variable.</p>
<p>In our case there is one coefficient of determination in our regression analysis in particular, that differs from the others. Looking at the table, it appears that the data of the regions in Bulgaria has an explanatory power of 0.973, meaning that the independent variable of economic regional growth explain the dependent variable of regional inequality to a greater extent and it may seem like there is a strong correlation between these variables. This can be presented in a scatter plot with a fitted line, for the sake of visualization, as shown below. We also observe that the p-value for the slope coefficient p &gt; 0.001, which suggests we can reject the null hypothesis that there is no correlation concerning the dependent and independent variable for the regression analysis of Bulgaria.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="Eurostat-EDA_files/figure-html/unnamed-chunk-41-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>For all the countries combined (CC) we have the coefficient of determination of 0.090, i.e.&nbsp;that the independent variable of economic regional growth, explains around 9% of the variance in the dependent variable regional inequality. This can also be visualized with scatter plots as shown below.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="Eurostat-EDA_files/figure-html/unnamed-chunk-42-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<p><img src="Eurostat-EDA_files/figure-html/unnamed-chunk-43-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="residuals-of-the-model" class="level3">
<h3 class="anchored" data-anchor-id="residuals-of-the-model">Residuals of the model</h3>
<p>Further, we want to graphically present the residuals of our model concerning the combined country data (CC). The residuals of the model is the difference between the observed value and mean value (slope coefficient) that the model predicts for that observation <span class="citation" data-cites="frostResiduals2022">(<a href="#ref-frostResiduals2022" role="doc-biblioref">Frost, 2022</a>)</span>.</p>
<div class="cell">

</div>
<div class="cell">
<div class="cell-output-display">
<p><img src="Eurostat-EDA_files/figure-html/unnamed-chunk-45-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Above we have plotted the residuals for our simple regression model in the scatter plot.</p>
</section>
<section id="classical-assumptions-ols" class="level3">
<h3 class="anchored" data-anchor-id="classical-assumptions-ols">Classical assumptions OLS</h3>
<p>Statistical analyses such as ordinary least squares regression (OLS) has underlying assumptions. It is when these classical assumptions are true, that OLS produces the best estimates. There are six classical assumptions for OLS regression. If the first four are fulfilled, our models are unbiased. All six assumptions are listed below:</p>
<ol type="1">
<li>Linearity: There must be a linear relationship between the dependent (<span class="math inline">\(Y_i\)</span>) and independent (<span class="math inline">\(X_i\)</span>) variables. As shown on our scatter plots with the fitted line, we see that the fitted line represents all plots as good as possible</li>
<li>Sample variation: There is variation in the independent variable (<span class="math inline">\(X_i\)</span>).</li>
<li>Random sampling: There is a random sample from the population of interest. Our data is collected from Eurostat, which is a reliable source in terms of random sampling.</li>
<li>Exogeneity: The explanatory variable (<span class="math inline">\(X_i\)</span>) is exogenous, i.e., it is not influenced by any other variables in the explanatory model.</li>
<li>Homoskedasticity: The error term (<span class="math inline">\(ε_i\)</span>) has the same variance for each value of the independent variable (<span class="math inline">\(X_i\)</span>).</li>
<li>Normality: The population error term (<span class="math inline">\(ε_i\)</span>) is normally distributed.</li>
</ol>
</section>
</section>
<section id="other-determinants-of-inequity" class="level2">
<h2 class="anchored" data-anchor-id="other-determinants-of-inequity">Other determinants of inequity</h2>
<p>According to the United Nations Statistics Division there are limitations to measuring regional inequity with GDP per capita as an indicator. GDP per capita does not account for or measure the social and environmental costs of production, and other social issues such as politics, education, health care and culture etc <span class="citation" data-cites="unitednationsstatisticsdivisionGROSSDOMESTICPRODUCT2007">(<a href="#ref-unitednationsstatisticsdivisionGROSSDOMESTICPRODUCT2007" role="doc-biblioref">Division, 2007</a>)</span>. It may be limited when measuring the level of overall well being in the population. It is therefore appropriate to look at other variables that can may have an impact and connection on regional inequity.</p>
<p>To explore further options to understand what variables that might effect regional inequity in our subset of countries, we have chosen 3 other datasets from Eurostat that we wish to explore further. These are concerning transport infrastructure, education and demographics. More specifically, we will in this part of the paper explore the effect of the number of motor- and railways, percentage of the population with higher education as well as life expectancy on regional inequity in the subset of countries. The analysis will be delimited by the fact we are only exploring the year of 2010, as mentioned previously.</p>
<div class="cell">

</div>
<section id="multiple-regression-model-austria" class="level3">
<h3 class="anchored" data-anchor-id="multiple-regression-model-austria">Multiple regression model Austria</h3>
<div class="cell">
<div class="cell-output-display">

<table class="huxtable" style="border-collapse: collapse; border: 0px; margin-bottom: 2em; margin-top: 2em; ; margin-left: auto; margin-right: auto;  " id="tab:unnamed-chunk-47"><caption>MRM AT</caption>
<colgroup><col><col><col><col><col><col></colgroup><tbody><tr>
<th style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0.8pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;"></th><th style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0.8pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">Model 1</th><th style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0.8pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">Model 2</th><th style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0.8pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">Model 3</th><th style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0.8pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">Model 4</th><th style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0.8pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">Model 5</th></tr>
<tr>
<th style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">Higher.educ</th><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">0.006&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">-0.002&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">0.007&nbsp;&nbsp;</td></tr>
<tr>
<th style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;"></th><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(0.012)</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(0.007)&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(0.008)&nbsp;</td></tr>
<tr>
<th style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">Number_of_MWAY_and_RL</th><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">0.000 **</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">0.000 **</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td></tr>
<tr>
<th style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;"></th><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(0.000)&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(0.000)&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td></tr>
<tr>
<th style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">Life.expec</th><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">-0.067 *</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">-0.068 *</td></tr>
<tr>
<th style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;"></th><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(0.023)&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(0.024)&nbsp;</td></tr>
<tr>
<th style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">const.</th><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">-0.011&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">0.007&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">0.041&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">5.553 *</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">5.518 *</td></tr>
<tr>
<th style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;"></th><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(0.207)</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(0.019)&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(0.106)&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(1.874)&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(1.917)&nbsp;</td></tr>
<tr>
<th style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">N</th><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">8&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">8&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">8&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">8&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">8&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td></tr>
<tr>
<th style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.8pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">R2</th><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.8pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">0.037&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.8pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">0.787&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.8pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">0.792&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.8pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">0.586&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.8pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">0.639&nbsp;&nbsp;</td></tr>
<tr>
<th colspan="6" style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0.8pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">Note:  *** p &lt; 0.001;  ** p &lt; 0.01;  * p &lt; 0.05 T statistics in brackets.</th></tr>
</tbody></table>

</div>
</div>
<p>In this table we have two multiple regression models and three simple regression models. Model 3 and 5 are the multiple regression models, whereas 1, 2 and 4 are simple regression models.</p>
<p>The multiple regression models for Austria show a coefficient of determination <span class="math inline">\(R^2\)</span> of 0.792 for Model 3 and 0.639 for Model 5, respectively. Model 3 concerns a multiple regression of percentage of the population with higher education and the number of railways and motorways as the independent variables, and the GINI coefficient as the dependent variable. Model 5 also has the percentage of the population with higher education as an independent variable, but has life expectancy as the second independent variable. Both models show significant correlation as the coefficient of determination <span class="math inline">\(R^2\)</span> &gt; 0.35.</p>
</section>
<section id="multiple-regression-model-belgium" class="level3">
<h3 class="anchored" data-anchor-id="multiple-regression-model-belgium">Multiple regression model Belgium</h3>
<div class="cell">
<div class="cell-output-display">

<table class="huxtable" style="border-collapse: collapse; border: 0px; margin-bottom: 2em; margin-top: 2em; ; margin-left: auto; margin-right: auto;  " id="tab:unnamed-chunk-48"><caption>MRM BE</caption>
<colgroup><col><col><col><col><col><col></colgroup><tbody><tr>
<th style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0.8pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;"></th><th style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0.8pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">Model 1</th><th style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0.8pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">Model 2</th><th style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0.8pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">Model 3</th><th style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0.8pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">Model 4</th><th style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0.8pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">Model 5</th></tr>
<tr>
<th style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">Higher.educ</th><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">-0.001&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">-0.001&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">0.000&nbsp;</td></tr>
<tr>
<th style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;"></th><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(0.003)</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(0.003)</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(0.004)</td></tr>
<tr>
<th style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">Number_of_MWAY_and_RL</th><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">-0.000&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">-0.000&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td></tr>
<tr>
<th style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;"></th><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(0.000)</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(0.000)</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td></tr>
<tr>
<th style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">Life.expec</th><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">-0.004&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">-0.005&nbsp;</td></tr>
<tr>
<th style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;"></th><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(0.011)</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(0.015)</td></tr>
<tr>
<th style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">const.</th><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">0.091&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">0.108&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">0.134&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">0.412&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">0.440&nbsp;</td></tr>
<tr>
<th style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;"></th><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(0.100)</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(0.049)</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(0.123)</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(0.861)</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(1.108)</td></tr>
<tr>
<th style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">N</th><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">7&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">7&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">7&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">7&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">7&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td></tr>
<tr>
<th style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.8pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">R2</th><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.8pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">0.006&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.8pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">0.095&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.8pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">0.107&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.8pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">0.030&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.8pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">0.031&nbsp;</td></tr>
<tr>
<th colspan="6" style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0.8pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">Note:  *** p &lt; 0.001;  ** p &lt; 0.01;  * p &lt; 0.05 T statistics in brackets.</th></tr>
</tbody></table>

</div>
</div>
<p>Furthermore, we want to look at how the multiple regression models for Belgium. In this table we see a much lower degree of explanation for the models, than that of Austria. It therefore suggests that the correlation between the independent and dependent variables is not as significant in comparison. A desired condition for correlation in regression models is that the coefficient of determination <span class="math inline">\(R^2\)</span> is equal to or higher than 0.35, which in these instances they are not.</p>
</section>
</section>
<section id="alternative-functional-forms" class="level2">
<h2 class="anchored" data-anchor-id="alternative-functional-forms">Alternative functional forms</h2>
<p>The third part of this explanatory data analysis paper mainly revolves around alternative functional forms which might fit our data of GDP per capita and Inequity better. This part will also mainly consist of regression analysis, but shall more specifically examine how our data fits when calculating the log of the independent variable <span class="math inline">\(X_i\)</span> (GDP per capita) and further if polynomial regression reinforces this connection. Like the second, this third part will deal with regions of NUTS2 level in our subset of countries.</p>
<section id="effect-of-development-for-different-subsets" class="level3">
<h3 class="anchored" data-anchor-id="effect-of-development-for-different-subsets">Effect of development for different subsets</h3>
<p>The first thing we will explore in this third part of the paper is to determine if the effect of development is significantly different for different subset of countries in our data set. To determine this we will create a dummy variable. A dummy variable is a variable used to explain qualitative values in a regression model. Dummy variables usually take binary values, i.e.&nbsp;0 or 1. We have chosen to use the data of Italy as the dummy variable, considering this is the country with most observations of 2010, and it is therefore the appropriate variable to compare with the rest of the data from all the other countries. We choose to multiply our dependent variable of the GINI coefficient by 10,000, so we get a better visualization of the slope coefficient.</p>
<div class="cell">
<div class="cell-output-display">

<table class="huxtable" style="border-collapse: collapse; border: 0px; margin-bottom: 2em; margin-top: 2em; ; margin-left: auto; margin-right: auto;  " id="tab:unnamed-chunk-49">
<colgroup><col><col><col></colgroup><tbody><tr>
<th style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0.8pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;"></th><th style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0.8pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">Italy</th><th style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0.8pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">All other countries</th></tr>
<tr>
<th style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(Intercept)</th><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">-391.284&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">1300.325 ***</td></tr>
<tr>
<th style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;"></th><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(229.306)&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(175.203)&nbsp;&nbsp;&nbsp;</td></tr>
<tr>
<th style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">GDP_capita_NUTS2</th><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">0.035 ***</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">-0.023 ***</td></tr>
<tr>
<th style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;"></th><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(0.009)&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(0.006)&nbsp;&nbsp;&nbsp;</td></tr>
<tr>
<th style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">N</th><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">34&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">37&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td></tr>
<tr>
<th style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">R2</th><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">0.330&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">0.316&nbsp;&nbsp;&nbsp;&nbsp;</td></tr>
<tr>
<th style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">FStat</th><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">15.792&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">16.151&nbsp;&nbsp;&nbsp;&nbsp;</td></tr>
<tr>
<th style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.8pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">PValue</th><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.8pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">0.000&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.8pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">0.000&nbsp;&nbsp;&nbsp;&nbsp;</td></tr>
<tr>
<th colspan="3" style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0.8pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">Note:  *** p &lt; 0.001;  ** p &lt; 0.01;  * p &lt; 0.05 T statistics in brackets.</th></tr>
</tbody></table>

</div>
</div>
<p>As seen from our table we have an appropriate distribution of observations, with Italy having 34 observations and the other countries combined having 37. We also see that the correlation between the dependent and the independent variable for the two regression models, that is the effect of regional economic development (<span class="math inline">\(X_i\)</span>) on regional inequality (<span class="math inline">\(Y_i\)</span>), are very similar. For Italy only we have a coefficient of determination of 0.33, compared to the other combined countries of 0.316. Based on this it suggests that the effect of regional economic development is not significantly different for different subsets of countries in our data set. The slope coefficient does however tell us that the effect is negative for Italy, and positive for the other combined countries, i.e.&nbsp;that higher regional development in Italy has the tendency to lead to greater inequality. For the other countries combined this trend is the opposite, that higher regional development decreases inequality.</p>
</section>
<section id="alternative-functional-forms-1" class="level3">
<h3 class="anchored" data-anchor-id="alternative-functional-forms-1">Alternative functional forms</h3>
<p>For this sub-task we will explore alternative functional forms of our previous estimates in the relationship between regional development <span class="math inline">\(y_j\)</span> on regional inequality <span class="math inline">\(GINIW_j\)</span>. More specifically we will estimate the log of GDP per capita in a linear regression model, and assign this variable as the new determinant of effect on regional economic development <span class="math inline">\(y_j\)</span>. According to Lessmann and Seidel, the level of economic development can be measured by the logarithm of GDP per capita <span class="citation" data-cites="lessmannRegionalInequalityConvergence2017">(<a href="#ref-lessmannRegionalInequalityConvergence2017" role="doc-biblioref">Lessmann and Seidel, 2017</a>)</span>. That is therefore the reason we will use the log of GDP per capita in our new estimates in the linear regression model, and we will determine if this fits our model better.</p>
<div class="cell">
<div class="cell-output-display">

<table class="huxtable" style="border-collapse: collapse; border: 0px; margin-bottom: 2em; margin-top: 2em; ; margin-left: auto; margin-right: auto;  " id="tab:unnamed-chunk-50">
<colgroup><col><col><col><col><col><col><col><col></colgroup><tbody><tr>
<th style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0.8pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;"></th><th style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0.8pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">AT</th><th style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0.8pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">BE</th><th style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0.8pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">BG</th><th style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0.8pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">HR</th><th style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0.8pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">IT</th><th style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0.8pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">SE</th><th style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0.8pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">CC</th></tr>
<tr>
<th style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">log_GDP_capita_NUTS2</th><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">-0.043&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">-0.048&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">0.168 ***</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">0.074 **</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">0.080&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">-0.023 *&nbsp;</td></tr>
<tr>
<th style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;"></th><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(0.107)</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(0.059)</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(0.014)&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(0.023)&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(0.066)</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(0.009)&nbsp;&nbsp;</td></tr>
<tr>
<th style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">const.</th><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">0.531&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">0.565&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">-1.287 ***</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">0.115 ***</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">-0.703 **</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">-0.819&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">0.286 **</td></tr>
<tr>
<th style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;"></th><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(1.107)</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(0.605)</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(0.117)&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(0.000)&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(0.231)&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(0.694)</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(0.087)&nbsp;&nbsp;</td></tr>
<tr>
<th style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">N</th><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">8&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">7&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">6&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">2&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">34&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">14&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">71&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td></tr>
<tr>
<th style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">R2</th><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">0.026&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">0.117&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">0.973&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">0.000&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">0.249&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">0.109&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">0.090&nbsp;&nbsp;&nbsp;</td></tr>
<tr>
<th style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">FStat</th><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">0.160&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">0.660&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">143.992&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">10.606&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">1.461&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">6.842&nbsp;&nbsp;&nbsp;</td></tr>
<tr>
<th style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.8pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">PValue</th><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.8pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">0.703&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.8pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">0.453&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.8pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">0.000&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.8pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.8pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">0.003&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.8pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">0.250&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.8pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">0.011&nbsp;&nbsp;&nbsp;</td></tr>
<tr>
<th colspan="8" style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0.8pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">Note:  *** p &lt; 0.001;  ** p &lt; 0.01;  * p &lt; 0.05 T statistics in brackets.</th></tr>
</tbody></table>

</div>
</div>
<p>As we can tell from the descriptive statistics of the regression models where the logarithm of GDP per capita has been assigned as the explanatory variable as compared to our previous simple regression models in part 2, with GDP per capita as the explanatory variable, the coefficients of determination has a slight tendency to be at a lower level. This applies more specifically to the regressions of Austria, Belgium, Italy and Sweden. The regression analysis of all the Countries Combined (CC) however has a slightly better <span class="math inline">\(R^2\)</span>, with the coefficient of 0.09, compared to 0.064 of the previous model. The scatterplot for the regression of the CC with the log of GDP per capita data is shown below.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="Eurostat-EDA_files/figure-html/unnamed-chunk-51-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Furthermore, we would like to present a polynomial regression analysis of our data. In these regressions we will still keep the logarithm of GDP per capita (<span class="math inline">\(X_i\)</span>) as our explanatory variable. The analysis consists of 2<sup>nd</sup> and 3<sup>rd</sup> degree polynomial regressions.</p>
<div class="cell">
<div class="cell-output-display">

<table class="huxtable" style="border-collapse: collapse; border: 0px; margin-bottom: 2em; margin-top: 2em; ; margin-left: auto; margin-right: auto;  " id="tab:unnamed-chunk-52">
<colgroup><col><col><col><col></colgroup><tbody><tr>
<th style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0.8pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;"></th><th style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0.8pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">Simple linear reg</th><th style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0.8pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">2nd degree polynomial</th><th style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0.8pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">3rd degree polynomial</th></tr>
<tr>
<th style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">log GDP per capita NUTS2</th><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">-0.023 *&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">-0.111&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">17.862 **</td></tr>
<tr>
<th style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;"></th><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(0.009)&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(0.227)</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(5.851)&nbsp;&nbsp;</td></tr>
<tr>
<th style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">log GDP per capita NUTS2 ^2</th><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">0.005&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">-1.900 **</td></tr>
<tr>
<th style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;"></th><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(0.012)</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(0.620)&nbsp;&nbsp;</td></tr>
<tr>
<th style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">log GDP capita NUTS2 ^3</th><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">0.067 **</td></tr>
<tr>
<th style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;"></th><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(0.022)&nbsp;&nbsp;</td></tr>
<tr>
<th style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">const.</th><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">0.286 **</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">0.698&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">-55.540 **</td></tr>
<tr>
<th style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;"></th><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(0.087)&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(1.067)</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(18.324)&nbsp;&nbsp;</td></tr>
<tr>
<th style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">N</th><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">71&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">71&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">71&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td></tr>
<tr>
<th style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">R2</th><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">0.090&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">0.092&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">0.204&nbsp;&nbsp;&nbsp;</td></tr>
<tr>
<th style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">FStat</th><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">6.842&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">3.454&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">5.738&nbsp;&nbsp;&nbsp;</td></tr>
<tr>
<th style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.8pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">PValue</th><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.8pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">0.011&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.8pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">0.037&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.8pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">0.001&nbsp;&nbsp;&nbsp;</td></tr>
<tr>
<th colspan="4" style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0.8pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">Note:  *** p &lt; 0.001;  ** p &lt; 0.01;  * p &lt; 0.05 T statistics in brackets.</th></tr>
</tbody></table>

</div>
</div>
<p>Comparing the simple linear regression with the polynomial regressions of 2<sup>nd</sup> and 3<sup>rd</sup> degree, we observe that the coefficient of determination increases. We can observe in particular that the 3<sup>rd</sup> degree polynomial regression show a significantly greater degree of explanation with an <span class="math inline">\(R^2\)</span> of 0.204, compared to 0.09 of the previous estimated model. Polynomial regression is however sensitive to outliers, which seems to be the case for our estimates.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="Eurostat-EDA_files/figure-html/unnamed-chunk-53-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<p><img src="Eurostat-EDA_files/figure-html/unnamed-chunk-54-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="breusch-pagan-test-heteroscedasticity" class="level3">
<h3 class="anchored" data-anchor-id="breusch-pagan-test-heteroscedasticity">Breusch Pagan Test (Heteroscedasticity)</h3>
<p>We will be using the Breush-Pagan test, to test for heteroskedasticity in linear regression models. When doing this test, the goal is to assert wether there is heteroscedasticity or homoscedasticity, which then will tell us wether the results of the regression are reliable or not.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>       BP 
0.9137468 </code></pre>
</div>
</div>
<p>Reading this output shows u a p-value(0.9137) that is above alpha (0.05), stating it is not significant. This gives us the conclusion that the we can keep the null-hypothesis and reject the A-hypothesis, further assuming the residuals of lm20 are <em>homoscedastic.</em></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>       BP 
0.9303437 </code></pre>
</div>
</div>
<p>This output from the second degree polynomial regression shows us similiar data as far as keeping the null-hypothesis and assuming <em>homoscedasticity</em> for the residuals. With a p-value(0.9303) higher than 0.05.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>       BP 
0.1250937 </code></pre>
</div>
</div>
<p>The third BP-test is a third degree polynomial regression showing us a lower p-value (0.1250937), but still within limits, and implying the same outcome as our previous bp-tests. Null-hypothesis stays, and further assuming that the residuals are <em>homoscedatistic.</em></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>       BP 
0.8762755 </code></pre>
</div>
</div>
<p>Our fourth, and second simple regression going through the Breusch Pagan Test, shows us a p-value (0.8762755) above our alpha (0.05) again, implying the residuals are <em>homoscedastistic</em> and our null-hypothesis stays.</p>
<p>We followed through with our given recommendations for how to solve this task of looking for heteroscedasticity, giving us the results as seen above. But we would like to add a note; According to Dr.&nbsp;Nisha Arora, <em>the Breusch Pagan Test assumes heteroscedasticity is a linear function of the independent variables.</em> Where if one would fail to find heteroscedisticity with the Breuch Pagan test, it would not necessarily mean that there is not a nonlinear relation between the error variance and the independent variables. Further it seems to be recommended to use the <em>White Test,</em> where as this test gives us a more flexible functional form that is suited for recognizing a greater amount of patterns for heteroscedasticity. The <em>White Test</em> also lets the independent variables to have a interactive and nonlinear effect on the error variance. <span class="citation" data-cites="aroraAnswerWhatCriterion2016">Arora (<a href="#ref-aroraAnswerWhatCriterion2016" role="doc-biblioref">2016</a>)</span> We followed through with our given recommendations for how to solve this task of looking for heteroscedasticity, giving us the results as seen above. But we would like to add a note; According to Dr.&nbsp;Nisha Arora, <em>the Breusch Pagan Test assumes heteroscedasticity is a linear function of the independent variables.</em> Where if one would fail to find heteroscedisticity with the Breuch Pagan test, it would not necessarily mean that there is not a nonlinear relation between the error variance and the independent variables. Further it seems to be recommended to use the <em>White Test,</em> where as this test gives us a more flexible functional form that is suited for recognizing a greater amount of patterns for heteroscedasticity. We followed through with our given recommendations for how to solve this task of looking for heteroscedasticity, giving us the results as seen above. But we would like to add a note to the test of the lm21 and lm22 which are not linear regressions. According to Dr.&nbsp;Nisha Arora, <em>the Breusch Pagan Test assumes heteroscedasticity is a linear function of the independent variables.</em> Where if one would fail to find heteroscedisticity with the Breuch Pagan test, it would not necessarily mean that there is not a nonlinear relation between the error variance and the independent variables. Further it seems to be recommended to use the <em>White Test,</em> where as this test gives us a more flexible functional form that is suited for recognizing a greater amount of patterns for heteroscedasticity. The <em>White Test</em> also lets the independent variables to have a interactive and nonlinear effect on the error variance <span class="citation" data-cites="aroraAnswerWhatCriterion2016">Arora (<a href="#ref-aroraAnswerWhatCriterion2016" role="doc-biblioref">2016</a>)</span>.</p>
<p>After feedback on our statement, we have removed the claim that lm21 and lm22 are not linear regressions. Further we add in that the <em>White test</em> can be used as a safety measure.</p>
</section>
</section>
<section id="potential-remedies-for-eventual-problems" class="level2">
<h2 class="anchored" data-anchor-id="potential-remedies-for-eventual-problems">Potential remedies for eventual problems</h2>
<p>Throughout this whole task we chose to target the most visible problem; economic inequality. Some countries and regions have a more visible gaps then other such as Sweden with the lowest inequality against Bulgaria with the highest. First of explaining what this means, in short, high GINI coefficients values implies that the income is spread uneven. That the greater amount of the income percentage in the area is earned by a fewer population. This over time will result in higher inequality gap even tho the general GDP per capita is rising. We will then see a reduction of middle class, where those who once were there, would either enter the upper class or the lower class, usually they will fall in to the latter category and the gap will expand.</p>
<p>There are several ways to reduce the income inequality within a country, and we see some of these implementations active in several countries today. The most common ones are government aid and policies in form of tax reliefs, income transfers( such as welfare programs, free health care, child support, housing support etc.). Considering the difference between the mentioned countries Sweden and Bulgaria, it is safe to assume that the priorities of the government in each of their respective countries are not aligned. Sweden, as the rest of Scandinavia, are well known for their governments strong priorities on social welfare, and benefiting all classes of society. Where in the Scandinavian countries one might be jobless and still make a living through their welfare system also known as ´trygd´. Where the individual for either medical or health reasons cannot contribute to society, you will still be granted enough to make a living. Social welfare is by all means, also in Bulgaria, but to a different degree, which we also believe could be on of the reasons for why the number of people who have left Bulgaria to work and live in other countries has doubled since they got rights to move freely in the EU <span class="citation" data-cites="networkHowManyBulgarians">Network (<a href="#ref-networkHowManyBulgarians" role="doc-biblioref">n.d.</a>)</span>.</p>
<p>Another factor that is also important towards perfect equality, is the minimum wages in the respective countries. Minimum wages in some countries are considered high wages in others, where as this comes down to mostly the countries economic state and in most cases is not comparable as easily. What one should compare, is countries minimum wage <em>against</em> normal/living wages. Reducing the gap between minimum wage, and the average for wage for normal/comfortable living will aid in reducing the population of the lower class and rise them up to middle class.</p>
<section id="causality" class="level3">
<h3 class="anchored" data-anchor-id="causality">Causality</h3>
<p>Causality appears when it is a velar cause-effect relationship between two variables. There is causation when A causes outcome B. a common mistake is to infer causality when correlation is present, but correlation is only a relationship.</p>
<p>The difference between Correlation and Causality is that when it is a correlation, we don’t know which way the relationship goes. It can also be a third variable that effects the correlation. In Causality variable A can predict variable B. We know the direction of the relationship. Its not possible to search for causality with the regression, it can only be used if a casual relationship is assumed.</p>
<p>To establish causality, two predictions need to be fufilled:</p>
<p>1.There needs to be a significant relationship, significant correlation.</p>
<p>2.a It needs to be a temporal sequence of the variables, variable A took place before variable B.</p>
<p>2.b Or if it is a theoretical justified and plausible theory which direction the causal relationship goes</p>
<p>From our models we find that the correlation between log GDP per Capita and GINI is not significant in total for all countries in the dataset. This means that we cannot for fill the first point to Causality. Furthermore, if the correlation where to be significant, we would argue that A (GDP per Capita) could not predict B (GINI/Inequality). Taking a starting point in that GINI is measured out from different regions, this means that it based on location and if GDP per Capita where to stay the same, the population of the regions could still move around resulting in changes in Inequality.</p>
<p>For example; if the population in the regions split equally around to make all regions have the same GDP per capita, the inequality between the regions would end up becoming lower. So there could be a correlation between X and Y, but Z could be the explanation for Y.</p>
</section>
</section>
<section id="references" class="level2">
<h2 class="anchored" data-anchor-id="references">References</h2>
<div id="refs" class="references csl-bib-body hanging-indent" data-line-spacing="2" role="doc-bibliography">
<div id="ref-AgrigentoItalyBritannica" class="csl-entry" role="doc-biblioentry">
<em>Agrigento | <span>Italy</span> | <span>Britannica</span></em>. (n.d.). Retrieved November 3, 2022, from <a href="https://www.britannica.com/place/Agrigento">https://www.britannica.com/place/Agrigento</a>
</div>
<div id="ref-AntwerpHistoryDiamonds" class="csl-entry" role="doc-biblioentry">
<em>Antwerp | <span>History</span>, <span>Diamonds</span>, <span>Port</span>, &amp; <span>Points</span> of <span>Interest</span> | <span>Britannica</span></em>. (n.d.). Retrieved November 2, 2022, from <a href="https://www.britannica.com/place/Antwerp-Belgium">https://www.britannica.com/place/Antwerp-Belgium</a>
</div>
<div id="ref-aroraAnswerWhatCriterion2016" class="csl-entry" role="doc-biblioentry">
Arora, D. N. (2016, June 9). <em>Answer to "<span>What</span> is criterion for <span>Breusch-Pagan</span> test?"</em>. <span>Cross Validated</span>. <a href="https://stats.stackexchange.com/a/218038">https://stats.stackexchange.com/a/218038</a>
</div>
<div id="ref-BolzanoBozenTrentinoAlto" class="csl-entry" role="doc-biblioentry">
<em>Bolzano - <span>Bozen</span>, <span>Trentino-Alto Adige</span>, <span>Italy</span></em>. (n.d.). Retrieved November 3, 2022, from <a href="https://www.italyheritage.com/regions/trentino/bolzano/bolzano.htm">https://www.italyheritage.com/regions/trentino/bolzano/bolzano.htm</a>
</div>
<div id="ref-brzozowskiBelgiumBreaks16month2020" class="csl-entry" role="doc-biblioentry">
Brzozowski, A. (2020, September 30). <em>Belgium breaks 16-month deadlock as new government formed</em>. <span>www.euractiv.com</span>. <a href="https://www.euractiv.com/section/politics/news/belgium-breaks-16-month-deadlock-as-new-government-formed/">https://www.euractiv.com/section/politics/news/belgium-breaks-16-month-deadlock-as-new-government-formed/</a>
</div>
<div id="ref-BurundiPopulation2022" class="csl-entry" role="doc-biblioentry">
<em>Burundi <span>Population</span> (2022) - <span>Worldometer</span></em>. (n.d.). Retrieved October 25, 2022, from <a href="https://www.worldometers.info/world-population/burundi-population/">https://www.worldometers.info/world-population/burundi-population/</a>
</div>
<div id="ref-CalabriaRegionItaly" class="csl-entry" role="doc-biblioentry">
<em>Calabria | region, <span>Italy</span> | <span>Britannica</span></em>. (n.d.). Retrieved November 3, 2022, from <a href="https://www.britannica.com/place/Catanzaro-Italy">https://www.britannica.com/place/Catanzaro-Italy</a>
</div>
<div id="ref-unitednationsstatisticsdivisionGROSSDOMESTICPRODUCT2007" class="csl-entry" role="doc-biblioentry">
Division, U. N. S. (2007). <em><span>GROSS DOMESTIC PRODUCT PER CAPITA</span></em>.
</div>
<div id="ref-EconomicRecoveryEU" class="csl-entry" role="doc-biblioentry">
<em>Economic recovery of <span>EU</span> regions after 2008</em>. (n.d.). Retrieved November 2, 2022, from <a href="https://ec.europa.eu/eurostat/web/products-eurostat-news/-/ddn-20191023-1">https://ec.europa.eu/eurostat/web/products-eurostat-news/-/ddn-20191023-1</a>
</div>
<div id="ref-Economy" class="csl-entry" role="doc-biblioentry">
<em>Economy</em>. (n.d.-a). Retrieved November 2, 2022, from <a href="https://www.istra-istria.hr/en/region-of-istria/general-information/economy/">https://www.istra-istria.hr/en/region-of-istria/general-information/economy/</a>
</div>
<div id="ref-Economya" class="csl-entry" role="doc-biblioentry">
<em>Economy</em>. (n.d.-b). <span>ŽUPANIJA DUBROVAČKO NERETVANSKA</span>. Retrieved November 2, 2022, from <a href="https://www.edubrovnik.org/en/economy/">https://www.edubrovnik.org/en/economy/</a>
</div>
<div id="ref-EconomyItaly" class="csl-entry" role="doc-biblioentry">
<em>Economy <span>In Italy</span></em>. (n.d.). <span>Live and Invest Overseas</span>. Retrieved November 3, 2022, from <a href="https://www.liveandinvestoverseas.com/country-hub/europe/italy/economy-in-italy/">https://www.liveandinvestoverseas.com/country-hub/europe/italy/economy-in-italy/</a>
</div>
<div id="ref-ewingItalyFallsBack2014" class="csl-entry" role="doc-biblioentry">
Ewing, J., and Pianigiani, G. (2014, August 6). Italy <span>Falls Back Into Recession</span>, <span>Raising Concern</span> for <span>Eurozone Economy</span>. <em>The New York Times: Business</em>. <a href="https://www.nytimes.com/2014/08/07/business/international/italy-falls-back-into-recession-raising-concern-for-eurozone-economy.html">https://www.nytimes.com/2014/08/07/business/international/italy-falls-back-into-recession-raising-concern-for-eurozone-economy.html</a>
</div>
<div id="ref-frostResiduals2022" class="csl-entry" role="doc-biblioentry">
Frost, J. (2022). Residuals. In <em>Statistics By Jim</em>.
</div>
<div id="ref-GDPConstant2015" class="csl-entry" role="doc-biblioentry">
<em><span>GDP</span> (constant 2015 <span>US</span>$) - <span>Burundi</span>, <span>Monaco</span> | <span>Data</span></em>. (n.d.). Retrieved October 25, 2022, from <a href="https://data.worldbank.org/indicator/NY.GDP.MKTP.KD?locations=BI-MC">https://data.worldbank.org/indicator/NY.GDP.MKTP.KD?locations=BI-MC</a>
</div>
<div id="ref-GlossaryNomenclatureTerritorial2021" class="csl-entry" role="doc-biblioentry">
<em>Glossary:<span>Nomenclature</span> of territorial units for statistics (<span>NUTS</span>)</em>. (2021, December 21). <a href="https://ec.europa.eu/eurostat/statistics-explained/index.php?title=Glossary:Nomenclature_of_territorial_units_for_statistics_(NUTS)">https://ec.europa.eu/eurostat/statistics-explained/index.php?title=Glossary:Nomenclature_of_territorial_units_for_statistics_(NUTS)</a>
</div>
<div id="ref-lessmannRegionalInequalityConvergence2017" class="csl-entry" role="doc-biblioentry">
Lessmann, C., and Seidel, A. (2017). Regional inequality, convergence, and its determinants <span>A</span> view from outer space. <em>European Economic Review</em>, <em>92</em>, 110–132. <a href="https://doi.org/10.1016/j.euroecorev.2016.11.009">https://doi.org/10.1016/j.euroecorev.2016.11.009</a>
</div>
<div id="ref-MilanHistoryPopulation" class="csl-entry" role="doc-biblioentry">
<em>Milan | <span>History</span>, <span>Population</span>, <span>Climate</span>, &amp; <span>Facts</span> | <span>Britannica</span></em>. (n.d.). Retrieved November 3, 2022, from <a href="https://www.britannica.com/place/Milan-Italy">https://www.britannica.com/place/Milan-Italy</a>
</div>
<div id="ref-MonacoPopulation2022" class="csl-entry" role="doc-biblioentry">
<em>Monaco <span>Population</span> (2022) - <span>Worldometer</span></em>. (n.d.). Retrieved October 25, 2022, from <a href="https://www.worldometers.info/world-population/monaco-population/">https://www.worldometers.info/world-population/monaco-population/</a>
</div>
<div id="ref-networkHowManyBulgarians" class="csl-entry" role="doc-biblioentry">
Network, E. D. J. (n.d.). <em>How many <span>Bulgarians</span> live in <span>Europe</span>? <span>And</span> what are the trends in their mobility?</em> <span>European Data Journalism Network</span>. Retrieved November 18, 2022, from <a href="https://www.europeandatajournalism.eu/eng/News/Data-news/How-many-Bulgarians-live-in-Europe-And-what-are-the-trends-in-their-mobility">https://www.europeandatajournalism.eu/eng/News/Data-news/How-many-Bulgarians-live-in-Europe-And-what-are-the-trends-in-their-mobility</a>
</div>
<div id="ref-romano2011CrisisItaly2021" class="csl-entry" role="doc-biblioentry">
Romano, S. (2021). The 2011 <span>Crisis</span> in <span>Italy</span>: <span>A Story</span> of <span>Deep-Rooted</span> (and <span>Still Unresolved</span>) <span>Economic</span> and <span>Political Weaknesses</span>. In B. De Souza Guilherme, C. Ghymers, S. Griffith-Jones, and A. Ribeiro Hoffmann (Eds.), <em>Financial <span>Crisis Management</span> and <span>Democracy</span>: <span>Lessons</span> from <span>Europe</span> and <span>Latin America</span></em> (pp. 173–184). <span>Springer International Publishing</span>. <a href="https://doi.org/10.1007/978-3-030-54895-7_10">https://doi.org/10.1007/978-3-030-54895-7_10</a>
</div>
<div id="ref-Serbia" class="csl-entry" role="doc-biblioentry">
<em>Serbia</em>. (n.d.). Retrieved November 2, 2022, from <a href="https://www.fn.no/Land/serbia">https://www.fn.no/Land/serbia</a>
</div>
<div id="ref-StatisticalRegionsEuropean" class="csl-entry" role="doc-biblioentry">
<em>Statistical regions in the <span>European Union</span> and partner countries</em>. (n.d.). 188.
</div>
<div id="ref-StatisticsEurostata" class="csl-entry" role="doc-biblioentry">
<em>Statistics | <span>Eurostat</span></em>. (n.d.). Retrieved November 2, 2022, from <a href="https://ec.europa.eu/eurostat/databrowser/view/nama_10r_3gdp/default/table?lang=en">https://ec.europa.eu/eurostat/databrowser/view/nama_10r_3gdp/default/table?lang=en</a>
</div>
<div id="ref-StatisticsEurostat2022" class="csl-entry" role="doc-biblioentry">
<em>Statistics | <span>Eurostat</span></em>. (2022, April 18). <a href="https://ec.europa.eu/eurostat/databrowser/view/nama_10r_3gdp/default/table?lang=en">https://ec.europa.eu/eurostat/databrowser/view/nama_10r_3gdp/default/table?lang=en</a>
</div>
<div id="ref-StatisticsEurostat2022a" class="csl-entry" role="doc-biblioentry">
<em>Statistics | <span>Eurostat</span></em>. (2022, June 2). <a href="https://ec.europa.eu/eurostat/databrowser/view/demo_r_pjanaggr3/default/table?lang=en">https://ec.europa.eu/eurostat/databrowser/view/demo_r_pjanaggr3/default/table?lang=en</a>
</div>
<div id="ref-WhereBarlettaBarlettaAndriaTrani" class="csl-entry" role="doc-biblioentry">
<em>Where is <span>Barletta</span>, <span>Barletta-Andria-Trani</span>, <span>Italy</span> on <span>Map Lat Long Coordinates</span></em>. (n.d.). Retrieved November 3, 2022, from <a href="https://www.latlong.net/place/barletta-barletta-andria-trani-italy-29937.html">https://www.latlong.net/place/barletta-barletta-andria-trani-italy-29937.html</a>
</div>
</div>
</section>
<section id="appendix" class="level2">
<h2 class="anchored" data-anchor-id="appendix">Appendix</h2>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-1" class="anchored">

<table><caption>Table 1:  GDP per capita all countries </caption>
 <thead>
  <tr>
   <th style="text-align:left;">   </th>
   <th style="text-align:left;">      GDP </th>
   <th style="text-align:left;">   Population </th>
   <th style="text-align:left;">   GDP_capita </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;"> Min.   :   168.4 </td>
   <td style="text-align:left;"> Min.   :  20320 </td>
   <td style="text-align:left;"> Min.   : 1087 </td>
  </tr>
  <tr>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;"> 1st Qu.:  2497.2 </td>
   <td style="text-align:left;"> 1st Qu.: 162809 </td>
   <td style="text-align:left;"> 1st Qu.:16873 </td>
  </tr>
  <tr>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;"> Median :  6345.6 </td>
   <td style="text-align:left;"> Median : 272688 </td>
   <td style="text-align:left;"> Median :24901 </td>
  </tr>
  <tr>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;"> Mean   : 10254.6 </td>
   <td style="text-align:left;"> Mean   : 390740 </td>
   <td style="text-align:left;"> Mean   :23549 </td>
  </tr>
  <tr>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;"> 3rd Qu.: 10967.6 </td>
   <td style="text-align:left;"> 3rd Qu.: 417742 </td>
   <td style="text-align:left;"> 3rd Qu.:30653 </td>
  </tr>
  <tr>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;"> Max.   :181212.9 </td>
   <td style="text-align:left;"> Max.   :4355725 </td>
   <td style="text-align:left;"> Max.   :57525 </td>
  </tr>
</tbody>
</table>

</div>
</div>
</div>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      let href = ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
</div> <!-- /content -->



</body></html>